version: 2

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  ldflags:
  - -X github.com/IPA-CyberLab/h132/version.Version={{.Version}}
  - -X github.com/IPA-CyberLab/h132/version.Commit={{.Commit}}
  main: ./cmd/h132

archives:
- format: tar.gz
  name_template: >-
    {{ .ProjectName }}_
    {{- .Version }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
