name: go

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Test
      run: go test ./...
      env:
        SKIP_TPM_TESTS: "1"
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags/v')
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
